"""add study_sector to users

Revision ID: 141ffaa72f9d
Revises: 4ebe723922bb
Create Date: 2026-05-02 16:20:22.654183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141ffaa72f9d'
down_revision: Union[str, Sequence[str], None] = '4ebe723922bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('study_sector', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'study_sector')
    # ### end Alembic commands ###
