name: CI/CD Backend

on:
  push:
    branches:
      - main
      - dev
      - "feat/**"
      - "chore/**"
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"

jobs:
  ## Lint job
  lint-check-job:
    name: Lint with ruff
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install ruff
        run: pip install ruff

      - name: Ruff check
        run: ruff check .

      - name: Ruff format check
        run: ruff format --check .

  ## Newman test job
  newman-test-job:
    name: Test Newman
    runs-on: ubuntu-24.04
    needs: lint-check-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node Js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create reports directory
        run: mkdir -p tests/newman/reports

      - name: Run API
        run: |
          pip install -r requirements.txt && python main.py
      - name: Run test API MarketHub
        run: |
          newman run tests/newman/collections/markethub_collection.json \
            -e tests/newman/environment/environment_collection.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export tests/newman/reports/report.html \
            --reporter-htmlextra-title "MarketHub API Test Report" \
            --reporter-htmlextra-browser-title "MarketHub Tests"

      - name: Upload artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: tests/newman/reports/report.html
          retention-days: 30

      - name: Upload entire report folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-report
          path: tests/newman/reports
          retention-days: 30

  deploy-image-job:
    name: Build and push docker image
    runs-on: ubuntu-24.04
    needs:
      - lint-check-job
      - newman-test-job
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          labels: |
            org.opencontainers.image.title=Backend Markethub
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.authors=${{ github.actor }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max